name: learn-github-actions
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: utibeabasi6/nginx-website
      
